package:
  name: mendeleev
  version: "0.3.6"

source:
  hg_url: https://lukaszmentel@bitbucket.org/lukaszmentel/mendeleev
  hg_tag: v0.3.6

build:
  noarch: python
  entry_points:

    - element.py = mendeleev.mendeleev:clielement

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

channels:
  - lmmentel

requirements:
  build:
    - python
    - setuptools
    - numpy
    - sqlalchemy
    - pandas
    - pyfiglet
    - six

  run:
    - python
    - numpy
    - sqlalchemy
    - pandas
    - pyfiglet

test:
  # Python imports
  imports:
    - mendeleev

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - element.py --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - pytest

about:
  home: http://mendeleev.readthedocs.io/en/stable/
  summary: 'Python API with a database of atomic properties for elements in the periodic table'
  license: MIT License
  license_family: MIT
